baseURL = 'https://usac-recipes.netlify.app/'
languageCode = 'en-us'
title = 'Usac Recipes'
theme = "recipes"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  category = "categories"
  tag = "tags"