backend:
  name: github
  repo: spacekek/usac_recepten
  branch: main
  client_id: Ov23licCxvFs1Igm8Vds
media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "cooking"
    label: "Cooking Recipes"
    folder: "content/cooking"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "baking"
    label: "Baking Recipes"
    folder: "content/baking"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }