backend:
  name: github
  repo: "spacekek/usac_recepten"
  branch: main
media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "cooking"
    label: "Cooking Recipes"
    folder: "content/cooking"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - label: "Dietary"
        name: "dietary"
        widget: "select"
        multiple: true
        required: false
        options:
          - { label: "Vegetarian", value: "vegetarian" }
          - { label: "Vegan", value: "vegan" }
          - { label: "Vegan Possible", value: "vegan-possible" }
          - { label: "Meat Possible", value: "meat-possible" }
          - { label: "Gluten-Free", value: "gluten-free" }
          - { label: "Dairy-Free", value: "dairy-free" }
          - { label: "Nut-Free", value: "nut-free" }
          - { label: "Soy-Free", value: "soy-free" }
      - label: "Method"
        name: "method"
        widget: "select"
        multiple: true
        required: false
        options:
          - { label: "One Pot", value: "one-pot" }
          - { label: "Oven", value: "oven" }
          - { label: "Make Ahead", value: "make-ahead" }
          - { label: "Easy", value: "easy" }
          - { label: "Advanced", value: "advanced" }
      - label: "Characteristics"
        name: "characteristics"
        widget: "select"
        multiple: true
        required: false
        options:
          - { label: "Creamy", value: "creamy" }
          - { label: "Spicy", value: "spicy" }
          - { label: "Hearty", value: "hearty" }
          - { label: "Light", value: "light" }
      - { label: "Servings", name: "servings", widget: "number", default: 4, min: 1, required: false }
      - { label: "Prep Time (minutes)", name: "prep_time", widget: "number", required: false }
      - { label: "Cook Time (minutes)", name: "cook_time", widget: "number", required: false }
      - { label: "Price Per Person (€)", name: "price_per_person", widget: "number", value_type: "float", step: 0.5, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "baking"
    label: "Baking Recipes"
    folder: "content/baking"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - label: "Dietary"
        name: "dietary"
        widget: "select"
        multiple: true
        required: false
        options:
          - { label: "Vegetarian", value: "vegetarian" }
          - { label: "Vegan", value: "vegan" }
          - { label: "Vegan Possible", value: "vegan-possible" }
          - { label: "Meat Possible", value: "meat-possible" }
          - { label: "Gluten-Free", value: "gluten-free" }
          - { label: "Dairy-Free", value: "dairy-free" }
          - { label: "Nut-Free", value: "nut-free" }
          - { label: "Soy-Free", value: "soy-free" }
      - label: "Method"
        name: "method"
        widget: "select"
        multiple: true
        required: false
        options:
          - { label: "No Oven", value: "no-oven" }
          - { label: "Easy", value: "easy" }
          - { label: "Advanced", value: "advanced" }
      - label: "Meal Type"
        name: "meal_type"
        widget: "select"
        multiple: true
        required: false
        options:
          - { label: "Hot" , value: "hot" }
          - { label: "Cold", value: "cold" }
          - { label: "Snack", value: "snack" }
          - { label: "Dessert", value: "dessert" }
          - { label: "Cake", value: "cake" }
          - { label: "Pie", value: "pie" }
      - label: "Characteristics"
        name: "characteristics"
        widget: "select"
        multiple: true
        required: false
        options:
          - { label: "creamy", value: "creamy" }
          - { label: "fruity", value: "fruity" }
          - { label: "chocolatey", value: "chocolatey" }
          - { label: "nutty", value: "nutty" }
      - { label: "Servings", name: "servings", widget: "number", default: 4, min: 1, required: false }
      - { label: "Prep Time (minutes)", name: "prep_time", widget: "number", required: false }
      - { label: "Baking Time (minutes)", name: "cook_time", widget: "number", required: false }
      - { label: "Price Per Person (€)", name: "price_per_person", widget: "number", value_type: "float", step: 0.5, required: false }
      - { label: "Body", name: "body", widget: "markdown" }